### ISSUE TITLE
Out of date dependencies cause Node-Gyp errors and prevent installation 

### ISSUE THREAD

**Issue by jordanlesich** [stevekinney/think-piece#30]
Hello, 

I'm trying to follow along with the tutorials on Front End Masters. I cannot clone and install this repo becasue of node-gyp errors. The culprit dependency seems to be firbase's grpc dependency. Here's the error from my console. 

> gyp ERR! stack     at ChildProcess.onExit (/home/jordan/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
> gyp ERR! System Linux 4.19.104-microsoft-standard
> gyp ERR! command "/home/jordan/.nvm/versions/node/v12.18.2/bin/node" "/home/jordan/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/jordan/repos/think-piece/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/jordan/repos/think-piece/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
> gyp ERR! cwd /home/jordan/repos/think-piece/node_modules/grpc
> gyp ERR! node -v v12.18.2
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/home/jordan/.nvm/versions/node/v12.18.2/bin/node /home/jordan/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/jordan/repos/think-piece/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/jordan/repos/think-piece/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/jordan/repos/think-piece/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> node-pre-gyp ERR! System Linux 4.19.104-microsoft-standard
> node-pre-gyp ERR! command "/home/jordan/.nvm/versions/node/v12.18.2/bin/node" "/home/jordan/repos/think-piece/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
> node-pre-gyp ERR! cwd /home/jordan/repos/think-piece/node_modules/grpc
> node-pre-gyp ERR! node -v v12.18.2
> node-pre-gyp ERR! node-pre-gyp -v v0.12.0
> node-pre-gyp ERR! not ok 
> Failed to execute '/home/jordan/.nvm/versions/node/v12.18.2/bin/node /home/jordan/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/jordan/repos/think-piece/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/jordan/repos/think-piece/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! grpc@1.18.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the grpc@1.18.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/jordan/.npm/_logs/2020-08-31T18_43_40_524Z-debug.log
> 

I've tried both yarn and npm. I'm running this on WSL 2 Ubuntu. This error prevents me from following along with the course.

**Comment by alvinlal** [comment]
`npm install firebase --force`  fixed it for me

**Comment by hpintos** [comment]
Hi! Did you managed to make this work? How? I think I might have some incompatibility with node version (v12.18.3)

**Comment by idivait** [comment]
For anyone stuck here, set the repo to use the lts of node dubnium in nvm and the install went smoothly: `nvm install --lts=dubnium && nvm use lts/dubnium` . I went for this specific release based off of the last commit to the repo.

**Comment by schapiroalexis** [comment]
following worked for me:
1) updated the firebase version.
2) removed lock file
3) sudo apt-get remove gyp

**Comment by nypinstripes** [comment]
@stevekinney was hoping we could get the deps updated.

**Comment by nypinstripes** [comment]
nevermind the nvm approach from @idivait worked, thanks.
